### ISSUE TITLE
Error downloading the template

### ISSUE THREAD

**Issue by phcamargo23** [vintasoftware/tapioca-wrapper#138]
In Windows, Python 2.7. Command `cookiecutter gh:vintasoftware/cookiecutter-tapioca`, return 
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\Scripts\cookiecutter-script.py", line 5, in <module>
    sys.exit(cookiecutter.cli.main())
  File "C:\ProgramData\Anaconda2\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda2\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda2\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\cookiecutter\cli.py", line 123, in main
    default_config=default_config,
  File "C:\ProgramData\Anaconda2\lib\site-packages\cookiecutter\main.py", line 63, in cookiecutter
    no_input=no_input,
  File "C:\ProgramData\Anaconda2\lib\site-packages\cookiecutter\repository.py", line 84, in determine_repo_dir
    no_input=no_input,
  File "C:\ProgramData\Anaconda2\lib\site-packages\cookiecutter\vcs.py", line 123, in clone
    stderr=subprocess.STDOUT,
  File "C:\ProgramData\Anaconda2\lib\subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'git', u'clone', u'https://github.com/vintasoftware/cookiecutter-tapioca.git']' returned non-zero exit status 128
```

**Comment by pavankumarinfo** [comment]
I am also facing similar issue with command "cookiecutter https://github.com/drivendata/cookiecutter-data-science". can please advise on solution.

**Comment by pacm93** [comment]
Do you have [Git](https://git-scm.com/) installed?
